# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-15 22:16
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('lastmod', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[(b'draft', b'drafting'), (b'edit', b'editor'), (b'publish', b'published')], max_length=24)),
                ('content', ckeditor.fields.RichTextField(max_length=20971520)),
                ('hitcount', models.IntegerField(default=0)),
                ('sharedcount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicetext', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(blank=True, upload_to=b'images')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[(b'draft', b'drafting'), (b'edit', b'editory'), (b'publish', b'published')], max_length=24)),
                ('recording', models.FileField(upload_to=b'podcasts')),
                ('runtime', models.CharField(max_length=15)),
                ('filesize', models.IntegerField(default=0)),
                ('hitcount', models.IntegerField(default=0)),
                ('sharedcount', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maynardlabs.Image')),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2500, null=True)),
                ('birth_day', models.TextField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='VidMbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maynardlabs.Question'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maynardlabs.Image'),
        ),
    ]
